version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/app.dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/clean_gin_api
    env_file: .env
    container_name: clean-gin-web
    depends_on:
      - database

  database:
    build: 
      context: .
      dockerfile: ./docker/db.dockerfile
    environment:   
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_HOST: "%"
      container_name: clean-gin-db
    ports:
      - 33066:3308
    volumes:
      - clean_gin_db:/var/lib/mysql 

  adminer:
    image: adminer
    ports:
    - ${ADMINER_PORT}:8080

# persisted storage
volumes:
  clean_gin_db: