version: '3.0'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/app.dockerfile
    ports:
      - 9000:8080
    volumes:
      - .:/clean_gin_api
    depends_on:
      - database
    container_name: golang-docker-web
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'

  database:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: clean_gin_api-db
    container_name: golang-clean_gin_api-db
    ports:
      - 33066:3306
    volumes:
      - golang-docker-data:/var/lib/mysql 

 
  adminer:
        image: adminer
        ports:
          - 8081:8080

# persisted storage
volumes:
  golang-docker-data: