name: clean-gin-api

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Initialize the environment variables
      run: |
          echo "creating .env file"
          echo "SERVER_PORT=9000
          ENVIRONMENT=local
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=3306
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASS=${{ secrets.DB_PASS }}
          MAX_MULTIPART_MEMORY=10485760
          ADMINER_PORT=5001
          DEBUG_PORT=5002" >.env            
    - name: testing docker-compose build
      run: | 
       docker-compose build
    - run: docker-compose up -d
    - name: Validate if the service is working or not via health check api
      run: |
        sleep 120
        curl http://localhost:9000/health-check
    
  
